
server:
  port: 8088

---
spring:
  profiles: default
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: http://localhost:8080/.well-known/jwks.json
  cloud:
    gateway:
      routes:
        - id: product
          uri: http://localhost:8081
          predicates:
            - Path=/product/**
        - id: order
          uri: http://localhost:8082
          predicates:
            - Path=/order/**
        - id: delivery
          uri: http://localhost:8083
          predicates:
            - Path=/deliverys/**
        - id: marketing
          uri: http://localhost:8084
          predicates:
            - Path=/serveys/**
        - id: servicecenter
          uri: http://localhost:8081
          predicates:
            - Path=/customers/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---
spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: product
          uri: http://product:8080
          predicates:
            - Path=/product/**
        - id: order
          uri: http://order:8080
          predicates:
            - Path=/order/**
        - id: delivery
          uri: http://delivery:8080
          predicates:
            - Path=/deliveries/**
        - id: marketing
          uri: http://marketing:8080
          predicates:
            - Path=/serveys/**
        - id: servicecenter
          uri: http://servicecenter:8080
          predicates:
            - Path=/customers/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true
server:
  port: 8080